# Generated by Django 2.1.2 on 2018-11-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velhot', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discussion',
            new_name='Discussions',
        ),
    ]
