# Generated by Django 2.1.2 on 2018-11-22 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velhot', '0006_auto_20181121_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='new_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
