# Generated by Django 2.1.2 on 2018-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velhot', '0011_auto_20181128_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
